# Generated by Django 4.2.18 on 2025-01-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_expo_push_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expo_push_token',
        ),
    ]
