# Generated by Django 4.2.18 on 2025-01-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
