# Generated by Django 4.2.18 on 2025-01-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderequest',
            old_name='end_location',
            new_name='destination_location',
        ),
        migrations.AddField(
            model_name='riderequest',
            name='destination_latitude',
            field=models.DecimalField(decimal_places=6, default=40, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderequest',
            name='destination_longitude',
            field=models.DecimalField(decimal_places=6, default=-70, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderequest',
            name='start_latitude',
            field=models.DecimalField(decimal_places=6, default=40, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riderequest',
            name='start_longitude',
            field=models.DecimalField(decimal_places=6, default=-71.1, max_digits=9),
            preserve_default=False,
        ),
    ]
